version: '3.9'

services:

  java_app:
    container_name: java_app
    image: hibernate-spring-app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/hibernate_spring
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=dasv21
    depends_on:
      - java_db
      - java_jdk

  java_jdk:
    container_name: java_jdk
    image: eclipse-temurin:17_35-jdk
    volumes:
      - /usr/local/java/:/usr/local/java/

  java_db:
    container_name: java_db
    image: mysql:8.1.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dasv21
      - MYSQL_DATABASE=hibernate_spring
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
